name: Self-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_e2e:
    name: run_e2e
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [test01, test02, test03, test04]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: trigger ${{ matrix.target }} and wait for it
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GH_DISPATCH_TOKEN }}
          workflow_file_name: dispatch_workflow.yml
          ref: ${{ github.base_ref }}
          wait_interval: 3
          client_payload: '{"testsuite":"${{ matrix.target }}"}'
          propagate_failure: true # Fail current job if downstream job fails.
          trigger_workflow: true
          wait_workflow: true